/*
 *   Copyright (c) 2025 Edward Boggis-Rolfe
 *   All rights reserved.
 */
 
namespace rpc
{  
    enum encoding : uint64_t
    {
        enc_default = 0,    //equivelant to yas_binary
        yas_binary = 1,
        yas_compressed_binary = 2,
        //yas_text = 4,     //not really needed
        yas_json = 8        //we may have different json parsers that have a better implementation e.g. glaze
        // protocol_buffers = 16,
        // flat_buffers = 32,
        // mpi = 64
    };
}