#import "example_shared/example_shared.idl"
#import "example_import/example_import.idl"

namespace yyy
{
    interface i_example
    {
        error_code add(int a, int b, [out, by_value] int& c);
        error_code create_foo([out]rpc::shared_ptr<xxx::i_foo>& target);
        error_code create_baz([out]rpc::shared_ptr<xxx::i_baz>& val);

        error_code create_example_in_subordnate_zone([out]rpc::shared_ptr<yyy::i_example>& target, uint64_t new_zone_id);
        error_code create_example_in_subordnate_zone_and_set_in_host(uint64_t new_zone_id, const std::string& name);
        error_code create_multiple_inheritance([out]rpc::shared_ptr<xxx::i_baz>& target);
    
        error_code recieve_interface([out]rpc::shared_ptr<xxx::i_foo>& val);//can be null
        error_code give_interface([in]const rpc::shared_ptr<xxx::i_baz> val);//can be null
        error_code call_create_enclave_val(rpc::shared_ptr<i_host> host);//can be null
        error_code call_create_enclave(const rpc::shared_ptr<i_host>& host);//can be null

        error_code call_host_create_enclave_and_throw_away(bool run_standard_tests);
        error_code call_host_create_enclave([out] rpc::shared_ptr<i_example>& target, bool run_standard_tests);

        //live app registry, it should have sole responsibility for the long term storage of app shared ptrs
        error_code call_host_look_up_app_not_return(const std::string& name, bool run_standard_tests);
        error_code call_host_look_up_app(const std::string& name, [out] rpc::shared_ptr<i_example>& app, bool run_standard_tests);
        error_code call_host_look_up_app_not_return_and_delete(const std::string& name, bool run_standard_tests);
        error_code call_host_look_up_app_and_delete(const std::string& name, [out] rpc::shared_ptr<i_example>& app, bool run_standard_tests);
        error_code call_host_set_app(const std::string& name, [in] const rpc::shared_ptr<i_example>& app, bool run_standard_tests);
        error_code call_host_unload_app(const std::string& name);
        
        error_code send_interface_back([in]const rpc::shared_ptr<xxx::i_baz>& input, [out]rpc::shared_ptr<xxx::i_baz>& output);//can be null
        
        error_code get_host([out] rpc::shared_ptr<i_host>& app);
        error_code set_host([in] const rpc::shared_ptr<i_host>& app);
    };

    interface i_host
    {
        error_code create_enclave([out] rpc::shared_ptr<i_example>& target);

        //live app registry, it should have sole responsibility for the long term storage of app shared ptrs
        error_code look_up_app(const std::string& name, [out] rpc::shared_ptr<i_example>& app);
        error_code set_app(const std::string& name, [in] const rpc::shared_ptr<i_example>& app);
        error_code unload_app(const std::string& name);
  };
} 